Added validation on note creation.
nadiia-kobylinska/notes pull request #1
Opened 2022-01-28 00:18 UTC by nadiia-kobylinska

- [ ] Note title cannot be empty
- [ ] Limit the content field to 1000 characters
- [ ] Show how many characters the text entry limit is exceeded
- [ ] Do not allow to save the note if it is not valid

Improved the code a bit by replacing useState with useReducer.

2022-01-28 09:21 UTC, sologubd approved these changes
Looks good to me.
The only one thing. I suggest using a code formatter in order to have the same spaces and indents everywhere.

2022-01-28 10:52 UTC, Rastopyr requested changes

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +            dispatch({type: 'change', payload: { editMode: props.id}})
Предыдущий подход с условными операторами мне нравился больше. Если должно выполняться какое то одно условие то можно сделать ретурн в первом ифе.

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +        if (props.id && state.editMode && props.id === state.editMode) {
Удобнее будет читать если сделать условие которое остановит выполнение по невалидным критериям. А саму логику писать уже после

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
>              titleRef.current.focus();
Я правильно понимаю что этот эффект нужен для инициализации контента? Мне кажется что можно проинициализировать состояние более декларативно, и хук для этого не потребуется.

Нужна будет помощь с тем чтобы эту логику декомпозировать?

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +        try {
Какая часть логики тут может выбросить исключение?

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +            props.save({
Мне кажется что стоит пропсу назвать `onSave`

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +                }, hasNoteIndex);
А для чего тут используется hasNoteIndex? Мне кажется что там куда это событие отправляется, можно посчитать это значение.

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +                    content: state.content || "empty"
Видимо старый код, тк у нас заметки не могут быть пустыми то fallback к дефолтному контенту и title можно убрать, мне кажется

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +                    id: hasNoteIndex!==-1 ? state.editMode : Date.now(),
Глаз зацепился за расчет id.

Тк это дженерал компонент формы, то форма должна просто сабмитить контент, и это стоит отразить в контракте формы. Например `onSubmit`.  А расчет id уже должен быть на более высоком слое, который знает что эта заметка редактируется или сохраняется.

Можно это поправить в рамках другого ПР к след домашке

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
>      }
А какое назначение этого диспатча? Может данные, которые он диспатчит, так же можно проинициализировать более декларативно

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +    const isDisabled = state.content === "" || state.title === "" || state.percentCharTitle>100 || state.percentCharContent>100;
В редьюсере можно посчитать флаг `isValid`, мне кажется это там должно быть. Это же часть состояния формы.

2022-01-28 10:52 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +                    {!state.editMode ? "New Note" : "Edit Note"}
nit: Стоит вынести в переменную заголовок

2022-01-28 17:01 UTC, nadiia-kobylinska commented on src/components/notes-manage/form-view.js
>              titleRef.current.focus();
Да, этот эффект нужен при инициализации существующей редактируемой заметки. Пробовала без эффекта, но как-то не сложилось. 
Подскажи как можно переделать?

2022-01-28 17:19 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
>              titleRef.current.focus();
Для редьюсера можно сразу initialState сформировать из `note.content` и `note.title`.
Элементам на которые навешаны `titleRef` и `contentRef` можно передать контент через [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml).

А для фокуса есть `autofocus` аттрибут.

2022-01-30 01:34 UTC, nadiia-kobylinska commented
@Rastopyr 
Last updates:

- Renamed the variables and event names.
- Simplified logic for better readability. 
- Removed old code.
- Moved ID calculation from the form.
- Updated initialisation and removed unnecessary ‘dispatchs'.
- Cleared duplicate code. Combined contentEditable Divs into one component.
- Added useRef to save cursor position in EditDiv.

2022-01-30 15:07 UTC, Rastopyr requested changes

2022-01-30 15:07 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +    const initialState = {
Здорово что получилось разгрузить немного тот эффект. Но появилась еще одна проблема, на каждый рендер будет создаваться этот объект. Мелочь а не очень приятно. Мне кажется что это стоит перенести в callback useReducer где определяется начальное состояние

2022-01-30 15:07 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +        const result = validateTextLength(e,100);
В контексте валидации стоит явно передавать валидируемое значение а не событие. Иначе такую фунцию будет немного сложно тестировать.

И что важно, что название функции не согласуется с ее сигнатрой.

2022-01-30 15:07 UTC, Rastopyr commented on src/components/notes-manage/formReducer.jsx
> +            action.payload.isValid = isValid(state);
Мутировать данные точно не стоит. Лучше сделать через деструктуризацию строчкой ниже.

2022-01-30 15:07 UTC, Rastopyr commented on src/components/notes-manage/formReducer.jsx
> +        case 'change':
За этот `change` постояно глаз цепляется. Тут точно должно быть больше событий, но предлагаю в другом ПР)

2022-01-30 15:30 UTC, nadiia-kobylinska commented on src/components/notes-manage/formReducer.jsx
> +        case 'change':
согласна, переделаю)

2022-01-30 15:32 UTC, nadiia-kobylinska commented on src/components/notes-manage/formReducer.jsx
> +            action.payload.isValid = isValid(state);
`return {...state, ...action.payload, isValid: isValid(state)};`
я правильно поняла, как-то так?

2022-01-30 22:34 UTC, nadiia-kobylinska commented on src/components/notes-manage/form-view.js
> +        const result = validateTextLength(e,100);
Заменила на e.target. 
Есть ли смысл здесь использовать ref?

2022-01-30 22:40 UTC, nadiia-kobylinska commented on src/components/notes-manage/form-view.js
> +    const initialState = {
Перенесла. 
Столкнулась в результате с проблемой: после сохранения новой заметки не удаляется содержимое с полей, хотя state пустой. А вот если сохранить уже существующую заметку, то всё ок. Предполагаю, что проблема может быть связана с ref и dangerouslySetInnerHTML, но никак не могу найти решение

2022-01-30 22:42 UTC, nadiia-kobylinska commented on src/components/notes-manage/form-view.js
> +        try {
удалила, так как уже неуместно

2022-01-31 09:22 UTC, Rastopyr commented on src/components/notes-manage/formReducer.jsx
> +            action.payload.isValid = isValid(state);
```
const nextState = { ...state, ...action.payload }

reutnr { ...nextState, isValid: isValid(nextState)  }
```

2022-01-31 09:23 UTC, Rastopyr commented on src/components/notes-manage/formReducer.jsx
> +            action.payload.isValid = isValid(state);
Это если валидировать новый стейт, сейчас валидируется предыдущий

2022-01-31 09:29 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +        const result = validateTextLength(e,100);
Не сразу понял почему передается элемент)

Смотри, `calcCountChar` судя по имплементации мутирует элемент(добавляет подстветку). Нарушается контракт функции, то есть она делает не то что обещает, не только валидирует. Так же нарушается принцип единства ответственности.

С точки зрения валидации, функция должна принимать какое то значение, например текст, и возвращать результат валидации. А уже потом на основе результатов этой валидации нужно принимать решение, подсвечивать что то внутри элемента или нет.

2022-01-31 09:34 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +        const result = validateTextLength(e,100);
Так же, что меня немного смущает, что эта функция использует DOM api. Мне кажется что стоит использовать react рендеринг

2022-01-31 10:40 UTC, Rastopyr commented on src/components/notes-manage/form-view.js
> +    const initialState = {
Увидел что закомментирован вызов `resetForm`, думаю можно пока вернуть. А в след домашке порефакторить редьюсер и мне кажется что там получится пофиксить проблему

2022-01-31 15:05 UTC, nadiia-kobylinska commented on src/components/notes-manage/form-view.js
> +        const result = validateTextLength(e,100);
подчистила calcCountChar и вынесла подсветку в отдельную функцию (пока отключила её). 
Использовала DOM api так как мне нужно сохранять позицию курсора после подсветки текста.

2022-01-31 17:07 UTC, Rastopyr approved these changes

2022-01-31 18:39 UTC, merged