#2 Hooks && Context
nadiia-kobylinska/notes pull request #2
Opened 2022-02-18 20:54 UTC by nadiia-kobylinska

Разделена логика работы с заметками.
Интегрирована логику работы с заметками при помощи React.Context и useReducer.
Созданы интеграционные слои для компонентов которые отображают данные заметок или отправляют события.
Частично вынесена логика работы с формой.
Переименованы события. 
Стили чаcтично вынесены в отдельные файлы.
Приложение переписано с JS на TS. 
Добавлен Eslint.

первый коммит чисто технический с конфигами для ts и eslint.
e315d95 - главные изменения, интегрирована логика с помощью React.Context, useReducer.
f92796a - переименованы события и компоненты, исправлены мелкие баги, вынесены стили, переписаны на ts все оставшиеся компоненты.

2022-02-19 13:45 UTC, OlegKotsubko approved these changes
Это было не легко. К логике и архитектуре у меня нет вопросов. Я так понимаю это 100% выполнение ТЗ) Я бы посоветовал в jsLinter поставить ограничение кода в длину до 120 символов. Сам посмотрел как можно писать. Было познавательно.

2022-05-31 14:54 UTC, Rastopyr requested changes

2022-05-31 14:54 UTC, Rastopyr commented on src/store/reducers/NoteListReducer.ts
> +            setNotesDS(updatedNotes);
Це краще звідци прибрати. це  side-effect, а його краще прібирати з такого роду функцій. проблема  - на цю функцию стає дуже складно написати unit tests

2022-05-31 14:54 UTC, Rastopyr commented on src/store/reducers/NoteListReducer.ts
> +            setNotesDS(updatedNotes);
Це краще звідци прибрати. це side-effect, а його краще прібирати з такого роду функцій. проблема - на цю функцию стає дуже складно написати unit tests

2022-05-31 14:54 UTC, Rastopyr commented on src/store/reducers/NoteListReducer.ts
> +            setNotesDS(updatedNotes);
Це краще звідци прибрати. це side-effect, а його краще прібирати з такого роду функцій. проблема - на цю функцию стає дуже складно написати unit tests

2022-05-31 14:54 UTC, Rastopyr commented on src/types/Mode.ts
> +enum Mode {
nit: цей enum можно покласти поруч reducer

2022-05-31 14:54 UTC, Rastopyr commented on src/types/Note.ts
> +  readonly mode: Mode;
Росскажи будь ласка, для чого тут використовуваєтся Mode?

2022-05-31 15:34 UTC, nadiia-kobylinska commented on src/types/Note.ts
> +  readonly mode: Mode;
Mode відповідав за відображення в'юшок, редагування чи превью

2022-06-01 20:31 UTC, Rastopyr commented on src/types/Note.ts
> +  readonly mode: Mode;
Зрозуміло, я хотів запропонувати перенести це в окремий стейт в наступному ПР, но побачів що ти вже це зробила в наступному ПР

2022-06-05 18:13 UTC, nadiia-kobylinska commented on src/types/Mode.ts
> +enum Mode {
в наступному пулреквесті прибрала

2022-06-05 20:00 UTC, Rastopyr approved these changes

2022-06-06 07:18 UTC, merged