Form && Routing
nadiia-kobylinska/notes pull request #3
Opened 2022-02-21 21:10 UTC by nadiia-kobylinska

Логику работы с формой вынесена в отдельную модель

2022-05-31 15:20 UTC, Rastopyr requested changes

2022-05-31 15:20 UTC, Rastopyr commented on src/components/Lobby.tsx
> +function Lobby({ children }: PageWrapperProps): JSX.Element {
nit: взагалі ти можешь використовувати тіпи реакту. `const Lobby: React.FC = (props) =>`

2022-05-31 15:20 UTC, Rastopyr commented on src/components/NoteForm/FormView.tsx
> +const Form = ({note, PageTitle, onCancel, onUpdate, onSave}:FormProps) => {
я би запропонував розділити view та логіку, на view та viewModel

2022-05-31 15:20 UTC, Rastopyr commented on src/pages/NoteDetail.tsx
> +    if (!!id){
`id !== undefined`?

2022-05-31 15:20 UTC, Rastopyr commented on src/pages/NoteForm.tsx
> +    if (!!id) {
if/else в єффектах підказує що у компонента можливо більш ніж одна віддповідальность. краще розділити раути яки відповідают за ці бранчі.

2022-05-31 15:20 UTC, Rastopyr commented on src/routes/index.tsx
> +      <Route path="notes/create" element={<NoteForm />} />
Ось тут е причина if/else в середині NoteForm

2022-05-31 15:20 UTC, Rastopyr commented on src/routes/index.tsx
> +      <Route path="/" element={<WelcomeRoute redirect={<Welcome />}><Navigate to="/notes"/></WelcomeRoute>}/>
Тут теж різні раути, а компонент один. Це можливо, буде створювати багато проблем потім

2022-06-05 20:25 UTC, Rastopyr commented on src/components/NoteForm/viewModel.tsx
> +    function onChangeContent(e:ChangeEvent<HTMLInputElement>){
В етом файлі є певна логіка, яку треба тестувати. Пропоную зробити ПР який буде виносити цю логіку за фасад

2022-06-05 20:58 UTC, nadiia-kobylinska commented on src/pages/NoteDetail.tsx
> +    if (!!id){
перевірка на` null/undefined` 

не зрозуміла, варто замінити?

2022-06-05 20:59 UTC, nadiia-kobylinska commented on src/pages/NoteForm.tsx
> +    if (!!id) {
else прибрала, залишинась перевірка id

2022-06-05 21:04 UTC, nadiia-kobylinska commented on src/routes/index.tsx
> +      <Route path="/" element={<WelcomeRoute redirect={<Welcome />}><Navigate to="/notes"/></WelcomeRoute>}/>
`WelcomeRoute` перевіряє чи є нотатки, від цього залежіть на яку сторінку потрапляємо, в результаті різні компоненти і різні посилання. Можливо назва `WelcomeRoute` не зовсім доречна.

2022-06-08 18:23 UTC, Rastopyr commented on src/pages/NoteDetail.tsx
> +    if (!!id){
З точки зору типів js там може бути 0, пуст астрока, та інши значення. Краще зробити explicit перевірку

2022-06-09 20:53 UTC, Rastopyr approved these changes

2022-06-10 08:30 UTC, merged